### ISSUE TITLE
v2.0 and sandbox.restore

### ISSUE THREAD

**Issue by ogdabou** [underscopeio/sinon-mongoose#18]
Hi ! First, thanks for your work !
  
I'm using sinon-mongoose with the sandbox feature.  
Mocking a model seems to work but only  once, that means `sandbox.restore` doesn't unwrap everything (or whatever sinon is doing).  

I looked at the tests in sinon-mongoose and it doesn't seem to test this use case.  

I tested it with `npm test` here : 
[link to test](https://github.com/ogdabou/sinon-mongoose/commit/e5302b77129f39b245edf727c0a7fed3acf803df)

**Comment by gaguirre** [comment]
Thanks @ogdabou!
What error are you getting? I've looked at your test but it is not obvious for me.

**Comment by ogdabou** [comment]
Hi !

Here it is : 
```
1) sinon-mongoose using sinon sandbox restore should restore sinon.sandbox:
     TypeError: Attempted to wrap find which is already wrapped
      at checkWrappedMethod (node_modules/sinon/lib/sinon/util/core/wrap-method.js:39:21)
      at wrapMethod (node_modules/sinon/lib/sinon/util/core/wrap-method.js:85:13)
      at Object.expects (node_modules/sinon/lib/sinon/mock.js:65:13)
      at Object.mock.expects (lib/index.js:9:1383)
      at Context.<anonymous> (test/index.js:96:19)
  --------------
  Error: Stack Trace for original
      at wrapMethod (node_modules/sinon/lib/sinon/util/core/wrap-method.js:110:26)
      at Object.expects (node_modules/sinon/lib/sinon/mock.js:65:13)
      at Object.mock.expects (lib/index.js:9:1383)
      at Context.<anonymous> (test/index.js:88:18)

  2) sinon-mongoose using sinon sandbox mocking should work mocking Model:
     TypeError: Attempted to wrap find which is already wrapped
      at checkWrappedMethod (node_modules/sinon/lib/sinon/util/core/wrap-method.js:39:21)
      at wrapMethod (node_modules/sinon/lib/sinon/util/core/wrap-method.js:85:13)
      at Object.expects (node_modules/sinon/lib/sinon/mock.js:65:13)
      at Object.mock.expects (lib/index.js:9:1383)
      at Context.<anonymous> (test/index.js:114:18)
  --------------
  Error: Stack Trace for original
      at wrapMethod (node_modules/sinon/lib/sinon/util/core/wrap-method.js:110:26)
      at Object.expects (node_modules/sinon/lib/sinon/mock.js:65:13)
      at Object.mock.expects (lib/index.js:9:1383)
      at Context.<anonymous> (test/index.js:88:18)
```  
Reading the messages I'm guessing something is set particular to `sinon-mongoose` and not reset when using `sandbox.restore()`

**Comment by gaguirre** [comment]
That's because you're mocking the same method twice before calling the _real_ method.
To make the test pass you should call to 
```
Book.find('SOME_ARGUMENTS').exec().then(function(result) {      
  assert.equal(result, 'RESULT');
})
``` 
before [this line](https://github.com/ogdabou/sinon-mongoose/commit/e5302b77129f39b245edf727c0a7fed3acf803df#diff-910eb6f57886ca16c136101fb1699231R92).

Tell me if that answer your question

**Comment by ogdabou** [comment]
Well thank you I didn't understand how to use this properly apparently !

Here is what is working: 
```
    it('should restore sinon.sandbox', () => {
        var sandbox = sinon.sandbox.create();
        var BookMock = sandbox.mock(Book);
        BookMock.expects('find')
          .withArgs('SOME_ARGUMENTS')
          .chain('exec')
          .resolves('RESULT');
        Book.find('SOME_ARGUMENTS').exec().then(function(result) {
          assert.equal(result, 'RESULT');
        });
        sandbox.verify();
        sandbox.restore();
        sandbox = sinon.sandbox.create();
        BookMock.expects('find')
          .withArgs('SOME_ARGUMENTS')
          .chain('exec')
          .resolves('RESULT2');
        Book.find('SOME_ARGUMENTS').exec().then(function(result) {
          assert.equal(result, 'RESULT2');
        });
      });
```

**Comment by gaguirre** [comment]
Great! Just to clarify, this is not related to `sandbox.mock()`. It will happen if you use `sinon.mock()` too.

**Comment by jniemin** [comment]
There was issue with sandbox.restore() not working properly. There is now new PR to fix this case
