### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by mauron85** [underscopeio/sinon-mongoose#45]
Just tried to run test on HEAD. There are 3 failed tests:

```
  1) sinon-mongoose
       should made Mongoose document methods chainables
         #verify chained:
     TypeError: Cannot read property 'events' of undefined
      at Query.exec (node_modules/.registry.npmjs.org/mongoose/5.4.16/node_modules/mongoose/lib/query.js:4078:17)
      at Context.<anonymous> (test/index.js:124:10)

  2) sinon-mongoose
       using sinon sandbox
         Verify chained - expectation.never():
     TypeError: Cannot read property 'events' of undefined
      at Query.exec (node_modules/.registry.npmjs.org/mongoose/5.4.16/node_modules/mongoose/lib/query.js:4078:17)
      at Context.<anonymous> (test/index.js:205:10)

  3) sinon-mongoose
       using sinon sandbox
         "after each" hook for "Verify chained - expectation.never()":
     ExpectationError: Expected limit([...]) once (never called)
      at Object.fail (node_modules/.registry.npmjs.org/sinon/6.1.0/node_modules/sinon/lib/sinon/mock-expectation.js:281:25)
      at Object.verify (node_modules/.registry.npmjs.org/sinon/6.1.0/node_modules/sinon/lib/sinon/mock.js:108:29)
      at Object.chainedVerify [as verify] (lib/index.js:58:20)
      at Object.chainedVerify [as verify] (lib/index.js:60:30)
      at Object.chainedVerify [as verify] (lib/index.js:60:30)
      at /Users/finch/dev/sinon-mongoose/node_modules/.registry.npmjs.org/sinon/6.1.0/node_modules/sinon/lib/sinon/sandbox.js:32:21
      at Array.filter (<anonymous>)
      at applyOnEach (node_modules/.registry.npmjs.org/sinon/6.1.0/node_modules/sinon/lib/sinon/sandbox.js:31:13)
      at Sandbox.verify (node_modules/.registry.npmjs.org/sinon/6.1.0/node_modules/sinon/lib/sinon/sandbox.js:340:9)
      at Context.<anonymous> (test/index.js:149:13)
```

**Comment by YasharF** [comment]
Tests seem to work fine for me.  Per error message you posted, it seems like that you are not running the tests on HEAD, since the error is stating "mongoose/5.4.16".  HEAD is at mongoose 5.1.7.  Did you run a command such as `npm audit fix` or regenerate package-lock.json?

**Comment by mauron85** [comment]
I've probably upgraded mongoose to test against latest. Closing for now.
