### ISSUE TITLE
Cannot read property '$handleCallbackError' of undefined

### ISSUE THREAD

**Issue by altairo2087** [underscopeio/sinon-mongoose#51]
**Dependencies:**
```
"mongoose": "5.7.3",
"sinon": "7.5.0",
"sinon-mongoose": "2.3.0",
```

**Sample app code**
```
const query = Car.find();
query.limit(10);
const rows = await query.lean();
```

**Test code:**
```
sinon.mock(Car)
      .expects('find')
      .chain('limit')
      .withArgs(10)
      .chain('lean')
      .resolves([]);
```

**Error**
```
      TypeError: Cannot read property '$handleCallbackError' of undefined
          at Query.exec (...\node_modules\mongoose\lib\query.js:4305:25)
          at Query.Object.<anonymous>.Query.then (...\node_modules\mongoose\lib\query.js:4367:15)
          at then (...\server\handlers\cars\list.js:51:37)
          at Object.list (...\server\handlers\cars\list.test.js:40:11)
          at Object.asyncJestTest (...\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
          at ...\node_modules\jest-jasmine2\build\queueRunner.js:43:12
          at new Promise (<anonymous>)
          at mapper (...\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
          at ...\node_modules\jest-jasmine2\build\queueRunner.js:73:41
          at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

If a remove `.chain('limit').withArgs(10)` there is no error

```
sinon.mock(Car)
      .expects('find')
      .chain('lean')
      .resolves([]);
```

**Comment by bidva** [comment]
I tried to add pagination meta to my method and faced a similar issue. actually, I have 2 different mongoose calls in my method and I get this error after adding the second call with countDocuments.

```
async list({ parentId, page = 1, perPage = 30}) {
    const options = { parentId };
    const query = this.find(options);
    
// the first find for actual records
    const data = await query
      .sort({ createdAt: -1 })
      .skip(perPage * (page - 1))
      .limit(perPage).exec();

// the second query with find to count documents
    const count = await query.countDocuments().exec();

    const meta = {
      page,
      perPage,
      total: count,
      totalPages: Math.ceil(count / perPage),
    };
    return {
      data,
      meta,
    };
  }
```

below code resolves the first call properly 

```
const jobs = [
        new Job(VALID_JOB),
        new Job(VALID_JOB_2),
      ];

jobMock.expects('find')
          .withArgs({})
          .chain('sort')
          .withArgs({ createdAt: -1 })
          .chain('skip')
          .withArgs(0)
          .chain('limit')
          .withArgs(30)
          .chain('exec')
          .resolves(jobs);

```
but not sure how to add the countDocuments to mock and resolve a number. I guess I need to mock it twice but it does not allow me.
