### ISSUE TITLE
Not compatible with Sinon 8.x

### ISSUE THREAD

**Issue by YasharF** [underscopeio/sinon-mongoose#58]
Changelog for Sinon: https://github.com/sinonjs/sinon/blob/master/CHANGELOG.md

The following is the error that appears when running the built-in tests after bumping Sinon in the dev dependency list to v8.0.2:

```
:/mnt/c/temp/sinon-mongoose$ npm test

> sinon-mongoose@2.3.0 test /mnt/c/temp/sinon-mongoose
> gulp

[13:46:14] Using gulpfile /mnt/c/temp/sinon-mongoose/gulpfile.js
[13:46:14] Starting 'default'...
[13:46:14] Starting 'static'...
[13:46:25] Finished 'static' after 10 s
[13:46:25] Starting 'test'...
[13:46:25] Starting 'pre-test'...
[13:46:25] Finished 'pre-test' after 112 ms
[13:46:25] Starting 'testTask'...
/mnt/c/temp/sinon-mongoose/lib/index.js:98
sinon.sandbox.mock = sandboxMock
                   ^

TypeError: Cannot set property 'mock' of undefined
    at Object.<anonymous> (/mnt/c/temp/sinon-mongoose/lib/index.js:98:20)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/mnt/c/temp/sinon-mongoose/test/index.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /mnt/c/temp/sinon-mongoose/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/mnt/c/temp/sinon-mongoose/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/mnt/c/temp/sinon-mongoose/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/mnt/c/temp/sinon-mongoose/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
-----------|----------|----------|----------|----------|----------------|
File       |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-----------|----------|----------|----------|----------|----------------|
 lib/      |    11.54 |        0 |        0 |    11.54 |                |
  index.js |    11.54 |        0 |        0 |    11.54 |... 91,92,95,98 |
-----------|----------|----------|----------|----------|----------------|
All files  |    11.54 |        0 |        0 |    11.54 |                |
-----------|----------|----------|----------|----------|----------------|


=============================== Coverage summary ===============================
Statements   : 11.54% ( 6/52 )
Branches     : 0% ( 0/19 )
Functions    : 0% ( 0/9 )
Lines        : 11.54% ( 6/52 )
================================================================================
[13:46:27] 'testTask' errored after 1.93 s
[13:46:27] Error in plugin "gulp-mocha"
Message:
    There were test failures
[13:46:27] 'test' errored after 2.05 s
[13:46:27] 'default' errored after 12 s
npm ERR! Test failed.  See above for more details.
```

**Comment by YasharF** [comment]
@andyesp, @aschenkel I noticed https://github.com/orgs/underscopeio/people isn't listing @gaguirre as part of the org.  This package, sinon-mongoose seems to need some love.  It currently doesn't work with the latest version of Sinon or Mongoose.  Is this something that underscopeio would like to continue own and maintain, or would you rather have the package moved to a different org?

Thank you!

**Comment by gaguirre** [comment]
Hi @YasharF, you already had permissions to merge PRs.
Let me know if that's not the case 😃

**Comment by YasharF** [comment]
I think I only have partial permissions.  The following is what is always showing up:
![image](https://user-images.githubusercontent.com/6448697/71739909-99539400-2e0f-11ea-89f8-f3b1c4a764dd.png)

**Comment by YasharF** [comment]
I managed to remove the dependency on sinon-mongoose in my projects this morning; you can probably remove my permissions to merge in this repo if there is one. Thank you.

**Comment by gaguirre** [comment]
Sorry for the trouble @YasharF, I just saw your comment. I thought you were able to merge.
I can transfer the repo ownership to you, would you accept it?
You're actively using it so I think it will be the best.

**Comment by YasharF** [comment]
I am no longer actively using sinon-mongoose as of about an hour ago.  I don't think if it would be a good idea to transfer it to me.  Perhaps @dhuang612 might be able to help.

**Comment by gaguirre** [comment]
@dhuang612 would you like that?

Again, sorry for the trouble @YasharF, it was never my idea. I thought you're already able to merge PRs 😞

**Comment by dhuang612** [comment]
sure I can take over the ownership of this repo

**Comment by gaguirre** [comment]
I can't transfer the repo from an organization to a user 🤷‍♂
Give me some time to figure out what it takes to make you owner, since it also involves `npm`  ownership.

**Comment by dhuang612** [comment]
sure thing no problem

**Comment by dhuang612** [comment]
@gaguirre hey reaching out to see if there are any updates?

Thanks

**Comment by suda** [comment]
Looks like Miro did the fix in #62. @gaguirre is it possible to add @dhuang612 as a maintainer so he could review/merge/release it?

**Comment by kdhttps** [comment]
Thanks to Miro. But as it is not updated on npm so I did the manual setup.

description is here https://stackoverflow.com/questions/62653523/sinon-mongoose-is-not-working-with-sinon-9/62654152#62654152

I hope it will help someone.

**Comment by simonnilsson** [comment]
Would be great if this could be fixed so one can update sinon.
