### ISSUE TITLE
Promise callback never invoked

### ISSUE THREAD

**Issue by hunthunt2010** [underscopeio/sinon-mongoose#9]
I am trying to write a unit test for my controllers using sinon-mongoose.  My test is as follows. 
```javascript 
var carrierController = require('../app_server/api_controllers/carrier');
var Carrier = require('../app_server/models/carrier');
var sinon = require('sinon');
var mongoose = require('mongoose');
require('sinon-as-promised');
require('sinon-mongoose');
it("list returns all carriers with sinon-mongoose", () => {
    var CarrierMock = sinon.mock(Carrier)
      .expects('find').withArgs({})
      .chain('exec')
      .resolves('SOMETHING');
    var response = {};
    carrierController.list({}, response);
    CarrierMock.verify();
  });
```

and my carriercontroller

```javascript 
var Carrier = require('../models/carrier');
var logger = require('../utils/logger');

module.exports = {
  list(req, res) {
    Carrier.find({}).exec()
      .then((carriers) => {
        console.log('carriers', carriers);
      });
  }
};
```

The problem I'm seeing is that the .then is never invoked inside of the controller

**Comment by gaguirre** [comment]
I don't know exactly if this is causing the issue but in this line
```javascript
var CarrierMock = sinon.mock(Carrier)
      .expects('find').withArgs({})
      .chain('exec')
      .resolves('SOMETHING');
```
you should separate the _instantiation_ from the _expectation_ like this
```javascript
var CarrierMock = sinon.mock(Carrier)
CarrierMock
      .expects('find').withArgs({})
      .chain('exec')
      .resolves('SOMETHING');
```
Otherwise you could not call to `CarrierMock.verify()` properly

**Comment by hunthunt2010** [comment]
I tried changing it to the code you suggested.  Still no luck. :(

**Comment by gaguirre** [comment]
Are you mocking the same `Carrier` model? Log it in your `list` method as follows and you should see that is mocked (copy/past the log result if you want help)
```javascript
list(req, res) {
    console.log(Carrier); // <-- add this line
    Carrier.find({}).exec()
      .then((carriers) => {
        console.log('carriers', carriers);
      });
  }
```

**Comment by hunthunt2010** [comment]
Thanks for the help so far.  Here is the log

```
{ [Function: model]
  hooks: Kareem { _pres: {}, _posts: {} },
  base: 
   Mongoose {
     connections: [ [Object] ],
     plugins: [],
     models: { Carrier: [Circular] },
     modelSchemas: { Carrier: [Object] },
     options: { pluralization: true } },
  modelName: 'Carrier',
  model: [Function: model],
  db: 
   NativeConnection {
     base: 
      Mongoose {
        connections: [Object],
        plugins: [],
        models: [Object],
        modelSchemas: [Object],
        options: [Object] },
     collections: { carriers: [Object] },
     models: { Carrier: [Circular] },
     config: { autoIndex: true },
     replica: false,
     hosts: null,
     host: null,
     port: null,
     user: null,
     pass: null,
     name: null,
     options: null,
     otherDbs: [],
     _readyState: 0,
     _closeCalled: false,
     _hasOpened: false,
     _listening: false },
  discriminators: undefined,
  schema: 
   Schema {
     paths: 
      { name: [Object],
        description: [Object],
        emailContact: [Object],
        _id: [Object],
        __v: [Object] },
     subpaths: {},
     virtuals: { id: [Object] },
     singleNestedPaths: {},
     nested: {},
     inherits: {},
     callQueue: [ [Object], [Object], [Object], [Object] ],
     _indexes: [],
     methods: {},
     statics: {},
     tree: 
      { name: [Object],
        description: [Object],
        emailContact: [Object],
        _id: [Object],
        id: [Object],
        __v: [Function: Number] },
     _requiredpaths: undefined,
     discriminatorMapping: undefined,
     _indexedpaths: undefined,
     query: {},
     childSchemas: [],
     s: { hooks: [Object], kareemHooks: [Object] },
     options: 
      { typeKey: 'type',
        id: true,
        noVirtualId: false,
        _id: true,
        noId: false,
        validateBeforeSave: true,
        read: null,
        shardKey: null,
        autoIndex: null,
        minimize: true,
        discriminatorKey: '__t',
        versionKey: '__v',
        capped: false,
        bufferCommands: true,
        strict: true,
        pluralization: true },
     '$globalPluginsApplied': true },
  collection: 
   NativeCollection {
     collection: null,
     opts: { bufferCommands: true, capped: false },
     name: 'carriers',
     collectionName: 'carriers',
     conn: 
      NativeConnection {
        base: [Object],
        collections: [Object],
        models: [Object],
        config: [Object],
        replica: false,
        hosts: null,
        host: null,
        port: null,
        user: null,
        pass: null,
        name: null,
        options: null,
        otherDbs: [],
        _readyState: 0,
        _closeCalled: false,
        _hasOpened: false,
        _listening: false },
     queue: [],
     buffer: true,
     emitter: 
      EventEmitter {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined } },
  Query: 
   { [Function]
     base: 
      Query {
        toConstructor: [Function: toConstructor],
        setOptions: [Function],
        collection: [Function: collection],
        '$where': [Function],
        where: [Function],
        equals: [Function: equals],
        eq: [Function: eq],
        or: [Function: or],
        nor: [Function: nor],
        and: [Function: and],
        gt: [Function],
        gte: [Function],
        lt: [Function],
        lte: [Function],
        ne: [Function],
        in: [Function],
        nin: [Function],
        all: [Function],
        regex: [Function],
        size: [Function],
        maxDistance: [Function],
        minDistance: [Function],
        mod: [Function],
        exists: [Function],
        elemMatch: [Function],
        within: [Function: within],
        box: [Function],
        polygon: [Function],
        circle: [Function],
        near: [Function: near],
        intersects: [Function: intersects],
        geometry: [Function: geometry],
        select: [Function: select],
        slice: [Function],
        sort: [Function],
        limit: [Function],
        skip: [Function],
        maxScan: [Function],
        batchSize: [Function],
        comment: [Function],
        maxTime: [Function],
        snapshot: [Function],
        hint: [Function],
        slaveOk: [Function],
        read: [Function],
        tailable: [Function],
        merge: [Function],
        find: [Function],
        cursor: [Function: cursor],
        findOne: [Function],
        count: [Function],
        distinct: [Function],
        update: [Function: update],
        remove: [Function],
        findOneAndUpdate: [Function],
        findOneAndRemove: [Function],
        _findAndModify: [Function],
        _wrapCallback: [Function],
        setTraceFunction: [Function],
        exec: [Function: exec],
        thunk: [Function],
        then: [Function],
        stream: [Function],
        selected: [Function: selected],
        selectedInclusively: [Function: selectedInclusively],
        selectedExclusively: [Function: selectedExclusively],
        _mergeUpdate: [Function],
        _optionsForExec: [Function],
        _fieldsForExec: [Function],
        _updateForExec: [Function],
        _ensurePath: [Function],
        _validate: [Function] } },
  '$__insertMany': [Function],
  insertMany: [Function],
  find: 
   { [Function]
     displayName: 'find',
     stackTrace: 'Error: Stack Trace for original\n    at Object.wrapMethod (/Users/Hunter/git/msearch/node_modules/sinon/lib/sinon/util/core.js:153:34)\n    at Object.expects (/Users/Hunter/git/msearch/node_modules/sinon/lib/sinon/mock.js:88:27)\n    at Object.mock.expects (/Users/Hunter/git/msearch/node_modules/sinon-mongoose/dist/index.js:23:37)\n    at Object.fit (/Users/Hunter/git/msearch/spec/carrierSpec.js:42:8)\n    at attemptSync (/Users/Hunter/git/msearch/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1950:24)\n    at QueueRunner.run (/Users/Hunter/git/msearch/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1938:9)\n    at QueueRunner.execute (/Users/Hunter/git/msearch/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1923:10)\n    at Spec.Env.queueRunnerFactory (/Users/Hunter/git/msearch/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:714:35)\n    at Spec.execute (/Users/Hunter/git/msearch/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:371:10)\n    at Object.fn (/Users/Hunter/git/msearch/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2579:37)\n    at attemptAsync (/Users/Hunter/git/msearch/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1980:24)\n    at QueueRunner.run (/Users/Hunter/git/msearch/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1935:9)\n    at QueueRunner.execute (/Users/Hunter/git/msearch/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1923:10)\n    at Env.queueRunnerFactory (/Users/Hunter/git/msearch/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:714:35)\n    at Object.fn (/Users/Hunter/git/msearch/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2564:13)\n    at attemptAsync (/Users/Hunter/git/msearch/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1980:24)',
     restore: { [Function] sinon: true } } }
```

**Comment by gaguirre** [comment]
Based on the last part of the log, the model is correctly mocked (look at the `find` method).
Now try expecting the method without args like follows
```javascript
var CarrierMock = sinon.mock(Carrier)
CarrierMock
      .expects('find')
      .chain('exec')
      .resolves('SOMETHING');
```

**Comment by hunthunt2010** [comment]
This is what I get without args
```
{ [Function: model]
  hooks: Kareem { _pres: {}, _posts: {} },
  base: 
   Mongoose {
     connections: [ [Object] ],
     plugins: [],
     models: { Carrier: [Circular] },
     modelSchemas: { Carrier: [Object] },
     options: { pluralization: true } },
  modelName: 'Carrier',
  model: [Function: model],
  db: 
   NativeConnection {
     base: 
      Mongoose {
        connections: [Object],
        plugins: [],
        models: [Object],
        modelSchemas: [Object],
        options: [Object] },
     collections: { carriers: [Object] },
     models: { Carrier: [Circular] },
     config: { autoIndex: true },
     replica: false,
     hosts: null,
     host: null,
     port: null,
     user: null,
     pass: null,
     name: null,
     options: null,
     otherDbs: [],
     _readyState: 0,
     _closeCalled: false,
     _hasOpened: false,
     _listening: false },
  discriminators: undefined,
  schema: 
   Schema {
     paths: 
      { name: [Object],
        description: [Object],
        emailContact: [Object],
        _id: [Object],
        __v: [Object] },
     subpaths: {},
     virtuals: { id: [Object] },
     singleNestedPaths: {},
     nested: {},
     inherits: {},
     callQueue: [ [Object], [Object], [Object], [Object] ],
     _indexes: [],
     methods: {},
     statics: {},
     tree: 
      { name: [Object],
        description: [Object],
        emailContact: [Object],
        _id: [Object],
        id: [Object],
        __v: [Function: Number] },
     _requiredpaths: undefined,
     discriminatorMapping: undefined,
     _indexedpaths: undefined,
     query: {},
     childSchemas: [],
     s: { hooks: [Object], kareemHooks: [Object] },
     options: 
      { typeKey: 'type',
        id: true,
        noVirtualId: false,
        _id: true,
        noId: false,
        validateBeforeSave: true,
        read: null,
        shardKey: null,
        autoIndex: null,
        minimize: true,
        discriminatorKey: '__t',
        versionKey: '__v',
        capped: false,
        bufferCommands: true,
        strict: true,
        pluralization: true },
     '$globalPluginsApplied': true },
  collection: 
   NativeCollection {
     collection: null,
     opts: { bufferCommands: true, capped: false },
     name: 'carriers',
     collectionName: 'carriers',
     conn: 
      NativeConnection {
        base: [Object],
        collections: [Object],
        models: [Object],
        config: [Object],
        replica: false,
        hosts: null,
        host: null,
        port: null,
        user: null,
        pass: null,
        name: null,
        options: null,
        otherDbs: [],
        _readyState: 0,
        _closeCalled: false,
        _hasOpened: false,
        _listening: false },
     queue: [],
     buffer: true,
     emitter: 
      EventEmitter {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined } },
  Query: 
   { [Function]
     base: 
      Query {
        toConstructor: [Function: toConstructor],
        setOptions: [Function],
        collection: [Function: collection],
        '$where': [Function],
        where: [Function],
        equals: [Function: equals],
        eq: [Function: eq],
        or: [Function: or],
        nor: [Function: nor],
        and: [Function: and],
        gt: [Function],
        gte: [Function],
        lt: [Function],
        lte: [Function],
        ne: [Function],
        in: [Function],
        nin: [Function],
        all: [Function],
        regex: [Function],
        size: [Function],
        maxDistance: [Function],
        minDistance: [Function],
        mod: [Function],
        exists: [Function],
        elemMatch: [Function],
        within: [Function: within],
        box: [Function],
        polygon: [Function],
        circle: [Function],
        near: [Function: near],
        intersects: [Function: intersects],
        geometry: [Function: geometry],
        select: [Function: select],
        slice: [Function],
        sort: [Function],
        limit: [Function],
        skip: [Function],
        maxScan: [Function],
        batchSize: [Function],
        comment: [Function],
        maxTime: [Function],
        snapshot: [Function],
        hint: [Function],
        slaveOk: [Function],
        read: [Function],
        tailable: [Function],
        merge: [Function],
        find: [Function],
        cursor: [Function: cursor],
        findOne: [Function],
        count: [Function],
        distinct: [Function],
        update: [Function: update],
        remove: [Function],
        findOneAndUpdate: [Function],
        findOneAndRemove: [Function],
        _findAndModify: [Function],
        _wrapCallback: [Function],
        setTraceFunction: [Function],
        exec: [Function: exec],
        thunk: [Function],
        then: [Function],
        stream: [Function],
        selected: [Function: selected],
        selectedInclusively: [Function: selectedInclusively],
        selectedExclusively: [Function: selectedExclusively],
        _mergeUpdate: [Function],
        _optionsForExec: [Function],
        _fieldsForExec: [Function],
        _updateForExec: [Function],
        _ensurePath: [Function],
        _validate: [Function] } },
  '$__insertMany': [Function],
  insertMany: [Function],
  find: 
   { [Function]
     displayName: 'find',
     stackTrace: 'Error: Stack Trace for original\n    at Object.wrapMethod (/node_modules/sinon/lib/sinon/util/core.js:153:34)\n    at Object.expects (/node_modules/sinon/lib/sinon/mock.js:88:27)\n    at Object.mock.expects (/node_modules/sinon-mongoose/dist/index.js:23:37)\n    at Object.fit (/spec/carrierSpec.js:42:8)\n    at attemptSync (/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1950:24)\n    at QueueRunner.run (/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1938:9)\n    at QueueRunner.execute (/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1923:10)\n    at Spec.Env.queueRunnerFactory (/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:714:35)\n    at Spec.execute (/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:371:10)\n    at Object.fn (/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2579:37)\n    at attemptAsync (/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1980:24)\n    at QueueRunner.run (/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1935:9)\n    at QueueRunner.execute (/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1923:10)\n    at Env.queueRunnerFactory (/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:714:35)\n    at Object.fn (/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2564:13)\n    at attemptAsync (/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1980:24)',
     restore: { [Function] sinon: true } } }
```

**Comment by hunthunt2010** [comment]
Found out this was an issue with jasmine.  We weren't calling done() in the proper place.  Have since decided not to use jasmine.  Thanks for all of the help!

**Comment by gaguirre** [comment]
Oh, these things can be tricky sometimes.
Good to hear you already solved your problem!
